let combos = {
    "fire water": "rock",
    "earth fire": "lava",
    "water water": "puddle",
    "air lava": "stone",
    "earth water": "mud",
    "fire mud": "brick",
    "brick brick": "wall",
    "fire stone": "metal",
    "air water": "rain",
    "earth rain": "plant",
    "air stone": "sand",
    "puddle puddle": "sea",
    "sea sea": "ocean",
    "fire water": "steam",
    "air steam": "cloud",
    "air earth": "dust",
    "dust fire": "gunpowder",
    "fire gunpowder": "kaboom"
}